# Generated by Django 3.2.3 on 2022-09-22 05:30

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='award')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=100)),
                ('time', models.CharField(choices=[('09300950', '9:30 am - 9:50 am'), ('10001020', '10:00 am - 10:20 am'), ('10301050', '10:30 am - 10:50 am')], max_length=128)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='update')),
                ('details', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
